# Generated by Django 5.1.2 on 2025-01-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('description', models.TextField()),
                ('published_date', models.DateField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('cover_image', models.ImageField(upload_to='covers/')),
                ('language', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('fantasy', 'Fantasy'), ('biography', 'Biography'), ('science_fiction', 'Science Fiction'), ('romance', 'Romance'), ('horror', 'Horror'), ('self_help', 'Self Help'), ('history', 'History')], max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
